#!/usr/bin/env node
/**
 * Capture 4 DISTINCT dashboard frames for Beacon demo video (Pulse design).
 * Frame 01: Full dashboard (hero + featured endpoints)
 * Frame 02: Cropped featured card close-up (probe bars + score)
 * Frame 03: Cropped compact rows + feed section
 * Frame 06: Branded closing card (generated separately by Python)
 *
 * Frames 04 (payment) and 05 (explorer) are terminal frames generated by Python.
 */
import puppeteer from 'puppeteer';
import { fileURLToPath } from 'url';
import path from 'path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FRAMES = path.join(__dirname, 'frames');
const URL = 'http://localhost:3001';

async function main() {
  const browser = await puppeteer.launch({ headless: 'new' });
  const page = await browser.newPage();

  await page.setViewport({ width: 1920, height: 1080 });
  await page.goto(URL, { waitUntil: 'networkidle2', timeout: 60000 });
  await new Promise(r => setTimeout(r, 10000)); // Wait for data + animations

  // Frame 01: Full dashboard overview
  await page.screenshot({ path: path.join(FRAMES, '01-dashboard.png') });
  console.log('OK 01-dashboard (full page)');

  // Frame 02: Cropped close-up of first featured card (hero gauge + top card)
  await page.screenshot({
    path: path.join(FRAMES, '02-feed.png'),
    clip: { x: 200, y: 80, width: 1520, height: 520 }
  });
  console.log('OK 02-feed (hero + top card close-up)');

  // Frame 03: Scroll down to compact rows + feed, crop that
  await page.evaluate(() => window.scrollTo(0, 700));
  await new Promise(r => setTimeout(r, 500));
  await page.screenshot({
    path: path.join(FRAMES, '03-scores.png'),
    clip: { x: 200, y: 0, width: 1520, height: 900 }
  });
  console.log('OK 03-scores (compact rows + feed)');

  await browser.close();
  console.log('Dashboard frames captured (3 distinct views)');
}

main().catch(err => { console.error(err); process.exit(1); });
