#!/usr/bin/env node
/**
 * Capture 4 DISTINCT dashboard frames for Beacon demo (Pulse design).
 * 01: Full dashboard (gauge + featured cards)
 * 02: Close-up of featured cards (probe bars + scores)
 * 03: Compact rows (dimmed dead endpoints) + feed section
 * 04-05: Terminal frames (generated by Python)
 * 06: Closing card (generated by Python)
 */
import puppeteer from 'puppeteer';
import { fileURLToPath } from 'url';
import path from 'path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FRAMES = path.join(__dirname, 'frames');
const URL = 'http://localhost:3001';

async function main() {
  const browser = await puppeteer.launch({ headless: 'new' });
  const page = await browser.newPage();

  // 1920x1080 viewport
  await page.setViewport({ width: 1920, height: 1080 });
  await page.goto(URL, { waitUntil: 'networkidle2', timeout: 60000 });
  await new Promise(r => setTimeout(r, 12000)); // Wait for data + entrance animations

  // Frame 01: Full dashboard overview (hero gauge + featured cards visible)
  await page.screenshot({ path: path.join(FRAMES, '01-dashboard.png') });
  console.log('OK 01-dashboard (full page with gauge + cards)');

  // Frame 02: Close-up of featured endpoint cards (crop to card area)
  // Cards start roughly at y=380 and span ~500px height
  await page.screenshot({
    path: path.join(FRAMES, '02-cards.png'),
    clip: { x: 180, y: 360, width: 1560, height: 600 }
  });
  console.log('OK 02-cards (featured cards close-up)');

  // Frame 03: Scroll far down to show compact rows + feed (must NOT show gauge/hero)
  await page.evaluate(() => window.scrollTo(0, 1100));
  await new Promise(r => setTimeout(r, 800));
  await page.screenshot({ path: path.join(FRAMES, '03-compact.png') });
  console.log('OK 03-compact (compact rows + feed)');

  await browser.close();
  console.log('All dashboard frames captured');
}

main().catch(err => { console.error(err); process.exit(1); });
